name: Deployment Workflow
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: SSH to server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /var/www/majoola-invitation-api-express
            eval `ssh-agent -s`
            ssh-add ~/.ssh/id_rsa
            git pull origin main
            git status
            npm install
            pm2 restart majoola-invitation-api-express --update-env
